inital_reset: true
enable_sync: true

# RGB
enable_color: true
rgb_camera.color_profile: 640x480x15
#rgb_camera.enable_auto_exposure: false

# Depth
enable_depth: true
depth_module.depth_profile: 640x480x15
align_depth.enable: true
clip_distance: 2.5

# IRs
enable_infra1: true
enable_infra2: true
depth_module.infra_profile: 640x480x15
depth_module.emitter_enabled: 0

# IMU
enable_gyro: true
enable_accel: true
gyro_fps: 400
accel_fps: 200
unite_imu_method: 2
hold_back_imu_for_frames: true
